name: wallet_flutter
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_serializable: ^6.1.3
  flutter_riverpod: ^1.0.3
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.wallet_flutter
    iosBundleIdentifier: com.example.walletFlutter
